### ISSUE TITLE
visualization incompatible

### ISSUE THREAD

**Issue by valencebond** [cpea2506/one_monokai.nvim#38]
visualization Not compatible in mac os 
<img width="1726" alt="截屏2023-02-19 16 38 14" src="https://user-images.githubusercontent.com/44313446/219937821-633a8325-b0e4-453e-83be-eb3550f3f3bd.png">

**Comment by cpea2506** [comment]
I'm not sure to understand your point. The preview image was taken from the macOS 😅

<img width="842" alt="Screenshot 2023-02-19 at 15 42 14" src="https://user-images.githubusercontent.com/42694704/219937880-f10570dc-6f86-482d-8153-d047022d917a.png">

**Comment by valencebond** [comment]
@cpea2506 I exactly follow your guidance. Are there some ways I can solve it? In my mac, this theme is also incompatible with nvim-tree
<img width="156" alt="截屏2023-02-19 16 46 54" src="https://user-images.githubusercontent.com/44313446/219938098-949468ff-8c44-4975-b531-d43782e63a21.png">

**Comment by cpea2506** [comment]
> @cpea2506 I exactly follow your guidance. Are there some ways I can solve it? In my mac, this theme is also incompatible with nvim-tree
> <img alt="截屏2023-02-19 16 46 54" width="156" src="https://user-images.githubusercontent.com/44313446/219938098-949468ff-8c44-4975-b531-d43782e63a21.png">

Ah. That's a problem with your terminal'font. You need to install [Nerd Font](https://www.nerdfonts.com/font-downloads)

**Comment by valencebond** [comment]
Thanks, I will try it.
