### ISSUE TITLE
feature: disable italics

### ISSUE THREAD

**Issue by Alyzmal** [cpea2506/one_monokai.nvim#55]
### Is your feature request related to a problem? Please describe.

I love the colors of this colorscheme, but I'm frustrated by the effect that the characters in italics have on their neighbors.

### Describe the solution you'd like

A blanket Lua setting to disable italics would be a very convenient way to solve this frustration.

### Describe alternatives you've considered

I have debated individually looking through the code to determine which highlight groups are italicized, but this would largely be ineffective and clutter up my personal configuration.

**Comment by cpea2506** [comment]
If I was right, you would want an option to disable all `italics`, like this:
```lua
require("one_monokai").setup({
	italics = false,
})
```
This will disable all italics, to enable `italics` for some of highlight group, you will need to use `themes` options.

**Comment by Alyzmal** [comment]
That is exactly what I'm after! I'm glad it was clear enough.

**Comment by cpea2506** [comment]
Thank you! All now done via #57 and it has been merged. You can now update and try it. If there is any problem araises, please let me know in other issue. 😄

**Comment by Alyzmal** [comment]
I'm sure it will work, I just need to wait for the NixNeovimPlugins Nix flake to recognize the update. It might require a version update, as it appears that the last time the plugin's flake was updated was on April 29, when version 1.2.0 of this plugin was released.

**Comment by Alyzmal** [comment]
The flake has finally updated and everything is working great! Thank you so much for your quick response and efforts!
